apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:latest
        ports:
        - containerPort: 5432

        
        env:
        - name: POSTGRES_DB
          value: testK8sdb

        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgresql-secrets
              key: POSTGRES_USERNAME

        - name: POSTGRES_PASSWORD     
          valueFrom:
            secretKeyRef:
              name: postgresql-secrets
              key: POSTGRES_PASSWORD         
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector: 
    app: postgresql
  ports:
  - port: 5432
    targetPort: 5432
